name: Cloud Run Service Image Deployment to Google Artifact Repository
on:
  push:
    branches:
      - main

jobs:
  go-binary-to-artifact-registry:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    permissions:
      contents: "read"
      id-token: "write"

    env:
      REGISTRY: "us-east4-docker.pkg.dev"
      PATH_TO_CONTAINER: "dragondrop-dev/dragondrop-https-triggers/cloud-run-service"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Google Authentication
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v2'
        with:
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ env.REGISTRY }}

      - name: Build and push API Container to Artifact Registry
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.PATH_TO_CONTAINER }}:latest --file=Dockerfile .
          docker push ${{ env.REGISTRY }}/${{ env.PATH_TO_CONTAINER }}:latest    
